/*
===============================================================================
Project Name : Retail Sales SQL Analytics
File Name    : 01_Sales_Analysis.sql
Author       : Manish Bokadia
Description  : Sales analysis using SQL to answer business questions.
===============================================================================
*/

-- =============================================================================
-- BUSINESS QUESTION 1
-- Find Total Sales
-- Objective: Calculate overall company revenue.
-- SQL Concepts: SUM()
-- =============================================================================
SELECT ROUND(SUM(sales),2) AS total_sales
FROM sales;
/*
Business Insight:
Provides the total revenue generated by the business and serves as the
baseline KPI for all further sales analysis.
*/

-- =============================================================================
-- BUSINESS QUESTION 2
-- Find Total Sales by Region
-- Objective: Identify the highest and lowest performing regions.
-- SQL Concepts: GROUP BY, SUM(), ORDER BY
-- =============================================================================
SELECT region,
       ROUND(SUM(sales),2) AS total_sales
FROM sales
GROUP BY region
ORDER BY total_sales DESC;
/*
Business Insight:
Highlights the strongest and weakest regions, helping management prioritize
marketing, inventory and expansion efforts.
*/

-- =============================================================================
-- BUSINESS QUESTION 3
-- Find Total Sales by Category
-- Objective: Compare category performance.
-- SQL Concepts: GROUP BY, SUM(), ORDER BY
-- =============================================================================
SELECT category,
       ROUND(SUM(sales),2) AS total_sales
FROM sales
GROUP BY category
ORDER BY total_sales DESC;
/*
Business Insight:
Shows which product categories drive revenue and which require attention.
*/

-- =============================================================================
-- BUSINESS QUESTION 4
-- Monthly Sales Trend
-- Objective: Track sales month by month.
-- SQL Concepts: YEAR(), MONTH(), GROUP BY
-- =============================================================================
SELECT YEAR(order_date) AS order_year,
       MONTH(order_date) AS order_month,
       ROUND(SUM(sales),2) AS total_sales
FROM sales
GROUP BY YEAR(order_date),MONTH(order_date)
ORDER BY order_year,order_month;
/*
Business Insight:
Helps identify seasonality, growth patterns and declining months.
*/

-- =============================================================================
-- BUSINESS QUESTION 5
-- Regional Sales Contribution
-- Objective: Calculate each region's contribution to company sales.
-- SQL Concepts: CTE, Window Function, SUM() OVER()
-- =============================================================================
WITH regional_sales AS (
SELECT region,SUM(sales) AS regional_sales
FROM sales
GROUP BY region)
SELECT region,
       ROUND(regional_sales,2) regional_sales,
       ROUND(regional_sales*100/SUM(regional_sales) OVER(),2) AS contribution_percentage
FROM regional_sales
ORDER BY contribution_percentage DESC;
/*
Business Insight:
Measures how much each region contributes to overall business revenue.
*/

-- =============================================================================
-- BUSINESS QUESTION 6
-- Running Sales Total by Month
-- Objective: Calculate cumulative sales.
-- SQL Concepts: CTE, SUM() OVER()
-- =============================================================================
WITH monthly_sales AS (
SELECT YEAR(order_date) order_year,
       MONTH(order_date) order_month,
       SUM(sales) total_sales
FROM sales
GROUP BY YEAR(order_date),MONTH(order_date))
SELECT order_year,
       order_month,
       ROUND(total_sales,2) monthly_sales,
       ROUND(SUM(total_sales) OVER(ORDER BY order_year,order_month),2) running_sales
FROM monthly_sales;
/*
Business Insight:
Tracks cumulative business growth over time and helps monitor long-term
sales performance.
*/
