
===============================================================================
                            RETAIL SALES SQL ANALYTICS
===============================================================================

File Name    : 1_Sales_Analysis.sql
Author       : Manish Bokadia
Database     : Retail Sales

Description:
This SQL script analyzes overall sales performance and answers key business
questions related to revenue, regional performance, category performance,
monthly trends, sales contribution, and cumulative sales.

===============================================================================
TABLE OF CONTENTS
===============================================================================

1. Find Total Sales
2. Find Total Sales by Region
3. Find Total Sales by Category
4. Analyze Monthly Sales Trend
5. Calculate Regional Sales Contribution (%)
6. Calculate Running Sales Total

===============================================================================



******************************************************************************
 BUSINESS QUESTION 1
*******************************************************************************

Question:
What is the total revenue generated by the company?

Business Objective:
Measure the total revenue generated from all sales transactions.

SQL Concepts Used:
• Aggregate Function
• SUM()


******************************************************************************/

SELECT
    ROUND(SUM(sales),2) AS total_sales
FROM sales;


Business Insight:

This KPI represents the total revenue generated by the business.
It is the most important metric for measuring overall business performance
and serves as the foundation for further sales analysis.



******************************************************************************
 BUSINESS QUESTION 2
*******************************************************************************

Question:
Which region generates the highest sales?

Business Objective:
Compare sales performance across different regions.

SQL Concepts Used:
• GROUP BY
• SUM()
• ORDER BY
       

******************************************************************************/

SELECT
    region,
    ROUND(SUM(sales),2) AS total_sales
FROM sales
GROUP BY region
ORDER BY total_sales DESC;


Business Insight:

This analysis identifies the best and worst performing regions.

Business can:
• Increase investment in high-performing regions.
• Investigate reasons behind poor-performing regions.
• Optimize marketing strategies region-wise.



******************************************************************************
 BUSINESS QUESTION 3
*******************************************************************************

Question:
Which product category generates the highest sales?

Business Objective:
Compare category-wise sales performance.

SQL Concepts Used:
• GROUP BY
• SUM()
• ORDER BY


******************************************************************************/

SELECT
    category,
    ROUND(SUM(sales),2) AS total_sales
FROM sales
GROUP BY category
ORDER BY total_sales DESC;


Business Insight:

This helps management understand which categories contribute the most revenue
and which categories require additional attention or promotional campaigns.



******************************************************************************
 BUSINESS QUESTION 4
*******************************************************************************

Question:
How do sales change over time?

Business Objective:
Analyze monthly sales trends.

SQL Concepts Used:
• YEAR()
• MONTH()
• GROUP BY
• ORDER BY



******************************************************************************/

SELECT

    YEAR(order_date) AS order_year,

    MONTH(order_date) AS order_month,

    ROUND(SUM(sales),2) AS total_sales

FROM sales

GROUP BY

    YEAR(order_date),

    MONTH(order_date)

ORDER BY

    order_year,

    order_month;


Business Insight:

Monthly trend analysis helps identify:

• Seasonality

• Peak business months

• Slow business months

• Business growth over time

These insights support forecasting and inventory planning.



******************************************************************************
 BUSINESS QUESTION 5
*******************************************************************************

Question:
How much does each region contribute to the company's total sales?

Business Objective:
Calculate the percentage contribution of every region.

SQL Concepts Used:
• CTE
• Window Functions
• SUM() OVER()


******************************************************************************/

WITH regional_sales AS

(

SELECT

    region,

    SUM(sales) AS regional_sales

FROM sales

GROUP BY region

)

SELECT

    region,

    ROUND(regional_sales,2) AS regional_sales,

    ROUND(

        regional_sales * 100

        /

        SUM(regional_sales) OVER(),

        2

    ) AS contribution_percentage

FROM regional_sales

ORDER BY contribution_percentage DESC;

/*
Business Insight:

Contribution percentage shows how much revenue each region contributes to the
overall company sales.

This helps management allocate:

• Marketing budget

• Sales resources

• Inventory

• Business expansion
*/


/******************************************************************************
 BUSINESS QUESTION 6
*******************************************************************************

Question:
What is the cumulative sales over time?

Business Objective:
Track business growth using a running total.

SQL Concepts Used:
• CTE
• Window Functions
• SUM() OVER()


******************************************************************************/

WITH monthly_sales AS

(

SELECT

    YEAR(order_date) AS order_year,

    MONTH(order_date) AS order_month,

    SUM(sales) AS total_sales

FROM sales

GROUP BY

    YEAR(order_date),

    MONTH(order_date)

)

SELECT

    order_year,

    order_month,

    ROUND(total_sales,2) AS monthly_sales,

    ROUND(

        SUM(total_sales) OVER(

            ORDER BY

            order_year,

            order_month

        ),

        2

    ) AS running_sales

FROM monthly_sales;

/*
Business Insight:

Running sales allows management to monitor cumulative business growth.

It helps answer questions like:

• Is the company growing consistently?

• At what point did sales accelerate?

• When did growth slow down?

Running totals are widely used in executive dashboards.
*/


/*
===============================================================================

END OF FILE

Total Business Questions : 6

SQL Concepts Covered:

✔ Aggregate Functions

✔ GROUP BY

✔ ORDER BY

✔ Date Functions

✔ CTE

✔ Window Functions

✔ Running Totals

✔ Contribution Analysis

===============================================================================
