
===============================================================================
                            RETAIL SALES SQL ANALYTICS
===============================================================================

File Name    : 6_ABC_Analysis.sql
Author       : Manish Bokadia
Database     : Retail Sales

Description:
ABC Analysis classifies products into Category A, B, and C based on their
contribution to total company sales.

Business Rule:

Category A → First 80% of cumulative sales
Category B → Next 15% of cumulative sales
Category C → Remaining 5%

===============================================================================
TABLE OF CONTENTS
===============================================================================

1. Calculate Product Sales
2. Calculate Running Sales
3. Calculate Company Sales
4. Calculate Running Percentage
5. Assign ABC Category
6. Final Business Report

===============================================================================



******************************************************************************
 STEP 1
*******************************************************************************

Question:
Calculate total sales for every product.

Business Objective:
Determine total revenue generated by each product.

SQL Concepts Used:
• GROUP BY
• SUM()

******************************************************************************/

WITH product_sales AS
(
    SELECT

        product_name,

        SUM(sales) AS total_sales

    FROM sales

    GROUP BY product_name
),

******************************************************************************
 STEP 2
*******************************************************************************

Question:
Calculate cumulative sales.

Business Objective:
Measure cumulative sales while ordering products
from highest to lowest sales.

SQL Concepts Used:
• Window Function
• SUM() OVER()

******************************************************************************/

running_sales AS
(
    SELECT

        *,

        SUM(total_sales)

        OVER(

            ORDER BY total_sales DESC

        ) AS running_total,

        SUM(total_sales)

        OVER() AS company_sales

    FROM product_sales
),

******************************************************************************
 STEP 3
*******************************************************************************

Question:
Calculate cumulative sales percentage.

Business Objective:
Measure cumulative percentage contribution
of every product.

SQL Concepts Used:
• CTE

******************************************************************************/

running_percentage AS
(
    SELECT

        *,

        ROUND(

            running_total*100/

            company_sales,

            2

        ) AS running_percentage

    FROM running_sales
)

******************************************************************************
 STEP 4
*******************************************************************************

Question:
Assign ABC Categories.

Business Objective:
Classify products according to
their contribution.

SQL Concepts Used:
• CASE

******************************************************************************/

SELECT

    product_name,

    ROUND(total_sales,2) AS total_sales,

    ROUND(running_total,2) AS running_total,

    ROUND(company_sales,2) AS company_sales,

    running_percentage,

    CASE

        WHEN running_percentage <=80

            THEN 'A'

        WHEN running_percentage <=95

            THEN 'B'

        ELSE 'C'

    END AS ABC_Category

FROM running_percentage

ORDER BY total_sales DESC;




===============================================================================

BUSINESS INSIGHT

Category A

• Highest revenue generating products

• Require strict inventory control

• Never allow stock-outs

• Highest business priority


------------------------------------------------------------


Category B

• Medium contribution products

• Moderate inventory monitoring

• Regular promotional activities


------------------------------------------------------------


Category C

• Lowest revenue generating products

• Keep minimum inventory

• Consider bundling, discounts,
  or discontinuation


------------------------------------------------------------


Business Benefits

✔ Better Inventory Planning

✔ Better Warehouse Management

✔ Improved Profitability

✔ Inventory Cost Reduction

✔ Focus on High Value Products

✔ Improved Supply Chain Planning

===============================================================================

END OF FILE

SQL Concepts Covered

✔ GROUP BY

✔ Aggregate Functions

✔ CTE

✔ Multiple CTE

✔ Window Functions

✔ SUM() OVER()

✔ CASE

✔ Running Totals

✔ Percentage Calculation

✔ ABC Analysis

===============================================================================

*/
